PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Test3(name TEXT NOT NULL, age INTEGER NOT NULL);
INSERT INTO Test3 VALUES('steve',58);
INSERT INTO Test3 VALUES('john',99);
INSERT INTO Test3 VALUES('joe',52);
COMMIT;
